name: helm
version: '2.6.1'
summary: The Kubernetes package manager
description: |
  Helm is a tool for managing Kubernetes
  charts. Charts are packages of
  pre-configured Kubernetes resources.

grade: stable
confinement: strict

apps:
  helm:
    command: helm
    environment:
        HELM_HOME: $SNAP_USER_COMMON
        KUBECONFIG: $SNAP_USER_COMMON/kube/config
    plugs:
      - network
      - home

parts:
  helm:
    plugin: dump
    source: https://storage.googleapis.com/kubernetes-helm/helm-v2.6.1-linux-amd64.tar.gz

